"""Initial migration

Revision ID: c36c1fb49213
Revises: 3944bcfe144a
Create Date: 2024-10-19 09:11:29.018196

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c36c1fb49213'
down_revision: Union[str, None] = '3944bcfe144a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'target_temperatures', ['device_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'target_temperatures', type_='unique')
    # ### end Alembic commands ###
