name: PlantUML Diagrams

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate PlantUML Diagrams
        uses: rotaract/plantuml-action@v1
        with:
          format: svg
          pattern: 'docs/puml_diagrams/*.puml'

      - name: Upload Diagrams
        uses: actions/upload-artifact@v4
        with:
          name: diagrams-${{ github.event.head_commit.message }}
          path: 'docs/**/*.svg'